/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  Skill as PrismaSkill,
  Project as PrismaProject,
} from "@prisma/client";

export class SkillServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.SkillCountArgs, "select">): Promise<number> {
    return this.prisma.skill.count(args);
  }

  async skills<T extends Prisma.SkillFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.SkillFindManyArgs>
  ): Promise<PrismaSkill[]> {
    return this.prisma.skill.findMany<Prisma.SkillFindManyArgs>(args);
  }
  async skill<T extends Prisma.SkillFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.SkillFindUniqueArgs>
  ): Promise<PrismaSkill | null> {
    return this.prisma.skill.findUnique(args);
  }
  async createSkill<T extends Prisma.SkillCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.SkillCreateArgs>
  ): Promise<PrismaSkill> {
    return this.prisma.skill.create<T>(args);
  }
  async updateSkill<T extends Prisma.SkillUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.SkillUpdateArgs>
  ): Promise<PrismaSkill> {
    return this.prisma.skill.update<T>(args);
  }
  async deleteSkill<T extends Prisma.SkillDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.SkillDeleteArgs>
  ): Promise<PrismaSkill> {
    return this.prisma.skill.delete(args);
  }

  async getProject(parentId: string): Promise<PrismaProject | null> {
    return this.prisma.skill
      .findUnique({
        where: { id: parentId },
      })
      .project();
  }
}
